
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.0
 * Query Engine version: 2ba551f319ab1df4bc874a89965d8b3641056773
 */
Prisma.prismaVersion = {
  client: "6.19.0",
  engine: "2ba551f319ab1df4bc874a89965d8b3641056773"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.ChallengeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  privateDescription: 'privateDescription',
  challengeSource: 'challengeSource',
  descriptionFormat: 'descriptionFormat',
  projectId: 'projectId',
  typeId: 'typeId',
  trackId: 'trackId',
  timelineTemplateId: 'timelineTemplateId',
  overviewTotalPrizes: 'overviewTotalPrizes',
  numOfRegistrants: 'numOfRegistrants',
  numOfSubmissions: 'numOfSubmissions',
  numOfCheckpointSubmissions: 'numOfCheckpointSubmissions',
  currentPhaseNames: 'currentPhaseNames',
  wiproAllowed: 'wiproAllowed',
  tags: 'tags',
  groups: 'groups',
  taskIsTask: 'taskIsTask',
  taskIsAssigned: 'taskIsAssigned',
  taskMemberId: 'taskMemberId',
  submissionStartDate: 'submissionStartDate',
  submissionEndDate: 'submissionEndDate',
  registrationStartDate: 'registrationStartDate',
  registrationEndDate: 'registrationEndDate',
  startDate: 'startDate',
  endDate: 'endDate',
  legacyId: 'legacyId',
  status: 'status',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengeTypeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  isActive: 'isActive',
  isTask: 'isTask',
  abbreviation: 'abbreviation',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengeTrackScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  isActive: 'isActive',
  abbreviation: 'abbreviation',
  legacyId: 'legacyId',
  track: 'track',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengeTimelineTemplateScalarFieldEnum = {
  id: 'id',
  typeId: 'typeId',
  trackId: 'trackId',
  timelineTemplateId: 'timelineTemplateId',
  isDefault: 'isDefault',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  challengeId: 'challengeId',
  fieldName: 'fieldName',
  oldValue: 'oldValue',
  newValue: 'newValue',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  memberId: 'memberId'
};

exports.Prisma.AttachmentScalarFieldEnum = {
  id: 'id',
  challengeId: 'challengeId',
  name: 'name',
  fileSize: 'fileSize',
  url: 'url',
  description: 'description',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengeMetadataScalarFieldEnum = {
  id: 'id',
  challengeId: 'challengeId',
  name: 'name',
  value: 'value',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.PrizeScalarFieldEnum = {
  id: 'id',
  description: 'description',
  prizeSetId: 'prizeSetId',
  type: 'type',
  value: 'value',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengeWinnerScalarFieldEnum = {
  id: 'id',
  challengeId: 'challengeId',
  userId: 'userId',
  handle: 'handle',
  placement: 'placement',
  type: 'type',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengeTermScalarFieldEnum = {
  id: 'id',
  challengeId: 'challengeId',
  termId: 'termId',
  roleId: 'roleId',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengeSkillScalarFieldEnum = {
  id: 'id',
  challengeId: 'challengeId',
  skillId: 'skillId',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengeBillingScalarFieldEnum = {
  id: 'id',
  billingAccountId: 'billingAccountId',
  markup: 'markup',
  clientBillingRate: 'clientBillingRate',
  challengeId: 'challengeId',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengeLegacyScalarFieldEnum = {
  id: 'id',
  reviewType: 'reviewType',
  confidentialityType: 'confidentialityType',
  forumId: 'forumId',
  directProjectId: 'directProjectId',
  screeningScorecardId: 'screeningScorecardId',
  reviewScorecardId: 'reviewScorecardId',
  isTask: 'isTask',
  useSchedulingAPI: 'useSchedulingAPI',
  pureV5Task: 'pureV5Task',
  pureV5: 'pureV5',
  selfService: 'selfService',
  selfServiceCopilot: 'selfServiceCopilot',
  track: 'track',
  subTrack: 'subTrack',
  legacySystemId: 'legacySystemId',
  challengeId: 'challengeId',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengeEventScalarFieldEnum = {
  id: 'id',
  challengeId: 'challengeId',
  eventId: 'eventId',
  name: 'name',
  key: 'key',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengeDiscussionScalarFieldEnum = {
  id: 'id',
  challengeId: 'challengeId',
  discussionId: 'discussionId',
  name: 'name',
  type: 'type',
  provider: 'provider',
  url: 'url',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengeDiscussionOptionScalarFieldEnum = {
  id: 'id',
  discussionId: 'discussionId',
  optionKey: 'optionKey',
  optionValue: 'optionValue',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengeConstraintScalarFieldEnum = {
  id: 'id',
  challengeId: 'challengeId',
  allowedRegistrants: 'allowedRegistrants',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.PhaseScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  isOpen: 'isOpen',
  duration: 'duration',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengePhaseScalarFieldEnum = {
  id: 'id',
  challengeId: 'challengeId',
  phaseId: 'phaseId',
  name: 'name',
  description: 'description',
  isOpen: 'isOpen',
  predecessor: 'predecessor',
  duration: 'duration',
  scheduledStartDate: 'scheduledStartDate',
  scheduledEndDate: 'scheduledEndDate',
  actualStartDate: 'actualStartDate',
  actualEndDate: 'actualEndDate',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengePhaseConstraintScalarFieldEnum = {
  id: 'id',
  challengePhaseId: 'challengePhaseId',
  name: 'name',
  value: 'value',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengePrizeSetScalarFieldEnum = {
  id: 'id',
  challengeId: 'challengeId',
  type: 'type',
  description: 'description',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengeReviewerScalarFieldEnum = {
  id: 'id',
  challengeId: 'challengeId',
  scorecardId: 'scorecardId',
  isMemberReview: 'isMemberReview',
  memberReviewerCount: 'memberReviewerCount',
  phaseId: 'phaseId',
  fixedAmount: 'fixedAmount',
  baseCoefficient: 'baseCoefficient',
  incrementalCoefficient: 'incrementalCoefficient',
  type: 'type',
  aiWorkflowId: 'aiWorkflowId',
  shouldOpenOpportunity: 'shouldOpenOpportunity',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.DefaultChallengeReviewerScalarFieldEnum = {
  id: 'id',
  typeId: 'typeId',
  trackId: 'trackId',
  timelineTemplateId: 'timelineTemplateId',
  scorecardId: 'scorecardId',
  isMemberReview: 'isMemberReview',
  memberReviewerCount: 'memberReviewerCount',
  phaseName: 'phaseName',
  phaseId: 'phaseId',
  fixedAmount: 'fixedAmount',
  baseCoefficient: 'baseCoefficient',
  incrementalCoefficient: 'incrementalCoefficient',
  opportunityType: 'opportunityType',
  aiWorkflowId: 'aiWorkflowId',
  shouldOpenOpportunity: 'shouldOpenOpportunity',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.TimelineTemplateScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  isActive: 'isActive',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.TimelineTemplatePhaseScalarFieldEnum = {
  id: 'id',
  timelineTemplateId: 'timelineTemplateId',
  phaseId: 'phaseId',
  predecessor: 'predecessor',
  defaultDuration: 'defaultDuration',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.MemberChallengeAccessScalarFieldEnum = {
  challengeId: 'challengeId',
  memberId: 'memberId'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.ChallengeOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  privateDescription: 'privateDescription',
  challengeSource: 'challengeSource',
  descriptionFormat: 'descriptionFormat',
  typeId: 'typeId',
  trackId: 'trackId',
  timelineTemplateId: 'timelineTemplateId',
  currentPhaseNames: 'currentPhaseNames',
  tags: 'tags',
  groups: 'groups',
  taskMemberId: 'taskMemberId',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengeTypeOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  abbreviation: 'abbreviation',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengeTrackOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  abbreviation: 'abbreviation',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengeTimelineTemplateOrderByRelevanceFieldEnum = {
  id: 'id',
  typeId: 'typeId',
  trackId: 'trackId',
  timelineTemplateId: 'timelineTemplateId',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.AuditLogOrderByRelevanceFieldEnum = {
  id: 'id',
  challengeId: 'challengeId',
  fieldName: 'fieldName',
  oldValue: 'oldValue',
  newValue: 'newValue',
  createdBy: 'createdBy',
  memberId: 'memberId'
};

exports.Prisma.AttachmentOrderByRelevanceFieldEnum = {
  id: 'id',
  challengeId: 'challengeId',
  name: 'name',
  url: 'url',
  description: 'description',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengeMetadataOrderByRelevanceFieldEnum = {
  id: 'id',
  challengeId: 'challengeId',
  name: 'name',
  value: 'value',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.PrizeOrderByRelevanceFieldEnum = {
  id: 'id',
  description: 'description',
  prizeSetId: 'prizeSetId',
  type: 'type',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengeWinnerOrderByRelevanceFieldEnum = {
  id: 'id',
  challengeId: 'challengeId',
  handle: 'handle',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengeTermOrderByRelevanceFieldEnum = {
  id: 'id',
  challengeId: 'challengeId',
  termId: 'termId',
  roleId: 'roleId',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengeSkillOrderByRelevanceFieldEnum = {
  id: 'id',
  challengeId: 'challengeId',
  skillId: 'skillId',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengeBillingOrderByRelevanceFieldEnum = {
  id: 'id',
  billingAccountId: 'billingAccountId',
  challengeId: 'challengeId',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengeLegacyOrderByRelevanceFieldEnum = {
  id: 'id',
  confidentialityType: 'confidentialityType',
  selfServiceCopilot: 'selfServiceCopilot',
  track: 'track',
  subTrack: 'subTrack',
  challengeId: 'challengeId',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengeEventOrderByRelevanceFieldEnum = {
  id: 'id',
  challengeId: 'challengeId',
  name: 'name',
  key: 'key',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengeDiscussionOrderByRelevanceFieldEnum = {
  id: 'id',
  challengeId: 'challengeId',
  discussionId: 'discussionId',
  name: 'name',
  provider: 'provider',
  url: 'url',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengeDiscussionOptionOrderByRelevanceFieldEnum = {
  id: 'id',
  discussionId: 'discussionId',
  optionKey: 'optionKey',
  optionValue: 'optionValue',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengeConstraintOrderByRelevanceFieldEnum = {
  id: 'id',
  challengeId: 'challengeId',
  allowedRegistrants: 'allowedRegistrants',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.PhaseOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengePhaseOrderByRelevanceFieldEnum = {
  id: 'id',
  challengeId: 'challengeId',
  phaseId: 'phaseId',
  name: 'name',
  description: 'description',
  predecessor: 'predecessor',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengePhaseConstraintOrderByRelevanceFieldEnum = {
  id: 'id',
  challengePhaseId: 'challengePhaseId',
  name: 'name',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengePrizeSetOrderByRelevanceFieldEnum = {
  id: 'id',
  challengeId: 'challengeId',
  description: 'description',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.ChallengeReviewerOrderByRelevanceFieldEnum = {
  id: 'id',
  challengeId: 'challengeId',
  scorecardId: 'scorecardId',
  phaseId: 'phaseId',
  aiWorkflowId: 'aiWorkflowId',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.DefaultChallengeReviewerOrderByRelevanceFieldEnum = {
  id: 'id',
  typeId: 'typeId',
  trackId: 'trackId',
  timelineTemplateId: 'timelineTemplateId',
  scorecardId: 'scorecardId',
  phaseName: 'phaseName',
  phaseId: 'phaseId',
  aiWorkflowId: 'aiWorkflowId',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.TimelineTemplateOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.TimelineTemplatePhaseOrderByRelevanceFieldEnum = {
  id: 'id',
  timelineTemplateId: 'timelineTemplateId',
  phaseId: 'phaseId',
  predecessor: 'predecessor',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.MemberChallengeAccessOrderByRelevanceFieldEnum = {
  challengeId: 'challengeId',
  memberId: 'memberId'
};
exports.ChallengeStatusEnum = exports.$Enums.ChallengeStatusEnum = {
  NEW: 'NEW',
  DRAFT: 'DRAFT',
  APPROVED: 'APPROVED',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  DELETED: 'DELETED',
  CANCELLED: 'CANCELLED',
  CANCELLED_FAILED_REVIEW: 'CANCELLED_FAILED_REVIEW',
  CANCELLED_FAILED_SCREENING: 'CANCELLED_FAILED_SCREENING',
  CANCELLED_ZERO_SUBMISSIONS: 'CANCELLED_ZERO_SUBMISSIONS',
  CANCELLED_WINNER_UNRESPONSIVE: 'CANCELLED_WINNER_UNRESPONSIVE',
  CANCELLED_CLIENT_REQUEST: 'CANCELLED_CLIENT_REQUEST',
  CANCELLED_REQUIREMENTS_INFEASIBLE: 'CANCELLED_REQUIREMENTS_INFEASIBLE',
  CANCELLED_ZERO_REGISTRATIONS: 'CANCELLED_ZERO_REGISTRATIONS',
  CANCELLED_PAYMENT_FAILED: 'CANCELLED_PAYMENT_FAILED'
};

exports.ChallengeTrackEnum = exports.$Enums.ChallengeTrackEnum = {
  DESIGN: 'DESIGN',
  DATA_SCIENCE: 'DATA_SCIENCE',
  DEVELOPMENT: 'DEVELOPMENT',
  QUALITY_ASSURANCE: 'QUALITY_ASSURANCE'
};

exports.PrizeSetTypeEnum = exports.$Enums.PrizeSetTypeEnum = {
  PLACEMENT: 'PLACEMENT',
  COPILOT: 'COPILOT',
  REVIEWER: 'REVIEWER',
  CHECKPOINT: 'CHECKPOINT'
};

exports.ReviewTypeEnum = exports.$Enums.ReviewTypeEnum = {
  COMMUNITY: 'COMMUNITY',
  INTERNAL: 'INTERNAL',
  SYSTEM: 'SYSTEM',
  PROVISIONAL: 'PROVISIONAL',
  EXAMPLE: 'EXAMPLE'
};

exports.DiscussionTypeEnum = exports.$Enums.DiscussionTypeEnum = {
  CHALLENGE: 'CHALLENGE'
};

exports.ReviewOpportunityTypeEnum = exports.$Enums.ReviewOpportunityTypeEnum = {
  REGULAR_REVIEW: 'REGULAR_REVIEW',
  COMPONENT_DEV_REVIEW: 'COMPONENT_DEV_REVIEW',
  SPEC_REVIEW: 'SPEC_REVIEW',
  ITERATIVE_REVIEW: 'ITERATIVE_REVIEW',
  SCENARIOS_REVIEW: 'SCENARIOS_REVIEW'
};

exports.Prisma.ModelName = {
  Challenge: 'Challenge',
  ChallengeType: 'ChallengeType',
  ChallengeTrack: 'ChallengeTrack',
  ChallengeTimelineTemplate: 'ChallengeTimelineTemplate',
  AuditLog: 'AuditLog',
  Attachment: 'Attachment',
  ChallengeMetadata: 'ChallengeMetadata',
  Prize: 'Prize',
  ChallengeWinner: 'ChallengeWinner',
  ChallengeTerm: 'ChallengeTerm',
  ChallengeSkill: 'ChallengeSkill',
  ChallengeBilling: 'ChallengeBilling',
  ChallengeLegacy: 'ChallengeLegacy',
  ChallengeEvent: 'ChallengeEvent',
  ChallengeDiscussion: 'ChallengeDiscussion',
  ChallengeDiscussionOption: 'ChallengeDiscussionOption',
  ChallengeConstraint: 'ChallengeConstraint',
  Phase: 'Phase',
  ChallengePhase: 'ChallengePhase',
  ChallengePhaseConstraint: 'ChallengePhaseConstraint',
  ChallengePrizeSet: 'ChallengePrizeSet',
  ChallengeReviewer: 'ChallengeReviewer',
  DefaultChallengeReviewer: 'DefaultChallengeReviewer',
  TimelineTemplate: 'TimelineTemplate',
  TimelineTemplatePhase: 'TimelineTemplatePhase',
  MemberChallengeAccess: 'MemberChallengeAccess'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
